// Generated by CoffeeScript 1.8.0
(function() {
  app.directive("login", function(connect, message, freelancer, lyric) {
    return {
      restrict: "C",
      controller: function($scope, $element) {
        var button;
        button = $element[0].querySelector("button");
        message.setNeutral(lyric.constant.message_6);
        return $scope.freelancer.loginer = function() {
          button.disabled = true;
          message.setNeutral(lyric.constant.message_7);
          return freelancer.login().then(function() {
            return null;
          }, function() {
            return button.disabled = false;
          });
        };
      }
    };
  });

  app.directive("scroll", function(scroll) {
    return {
      restrict: "A",
      controller: function($scope, $element) {
        return scroll.setElement({
          selector: $element[0]
        });
      }
    };
  });

}).call(this);
